# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/appbase_db
spring.datasource.username=appbase_user
spring.datasource.password=123qweasd

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ACTUATOR
management.endpoints.web.exposure.include=*
info.app.name=appbase
info.app.version=@project.version@
info.app.description=Backend REST de AppBase

# FRONTEND
app.cors.allowed-origins=http://localhost:5173