spring.application.name=appbase-rest
server.port=8080

# DATABASE (default - can be overridden with environment variables)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/appbase_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:appbase_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123qweasd}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# LOG
log.folder=../logs

logging.level.root=INFO
logging.level.dev.jmjimenez=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.springframework.boot=INFO
logging.level.org.springframework.boot.web.embedded.tomcat=INFO

# RATE LIMITING
ratelimit.general.limit=120
ratelimit.general.duration=1
ratelimit.login.limit=5
ratelimit.login.duration=5
ratelimit.ban.duration=20
ratelimit.trusted-proxies=

# SECURITY
#openssl rand -base64 64
jwt.secret=L3MwLdrVYWL1FNQ7uNIXJAkR+SLF42sRX6naKPqcQUxUJHV33iFy81M3j5ej+UmecrzkpSWT5afB4rFtmN79Og==
jwt.access.expiration=900000
jwt.refresh.expiration=604800000
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.http-only=true

# OPEN_API
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.operationsSorter=method

# CORS
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000
